### ISSUE TITLE
dateformat issue

### ISSUE THREAD

**Issue by simonsd054** [raralabs/react-patro#12]
When dateformat prop is used, error occurs.

Reproduction code:
`<Picker
    calendarType="AD"
    dateFormat="dd-mm-yyyy"
    //other props
/>`

Error: 
An error occurred: Invalid Date Format. Expected Date Format dd-mm-yyyy instead got 01-01-2022 for prop value passed in Calendar.

**Comment by ctrlx-altf4** [comment]
Couldn't recreate the issue!
